services:
  - type: web
    name: utme-cbt-server
    env: node
    plan: free
    region: oregon
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://Utmecbt:isaiahilom@1@utme.7jkkmin.mongodb.net/?retryWrites=true&w=majority&appName=Utme
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        fromService:
          type: static
          name: utme-cbt-client
          property: host
    healthCheckPath: /api/leaderboard

  - type: static
    name: utme-cbt-client
    env: node
    plan: free
    region: oregon
    branch: main
    rootDir: client
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: SERVER_URL
        fromService:
          type: web
          name: utme-cbt-server
          property: host
